

source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:wintersweet/MySpecs.git'
use_frameworks!

platform :ios, '9.0'

target 'FuseUI_Example' do
  pod 'FuseUI', :path => '../'

  target 'FuseUI_Tests' do
    inherit! :search_paths

    
  end
end
